/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { GymEquipmentCreateNestedManyWithoutGymsInput } from "./GymEquipmentCreateNestedManyWithoutGymsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsNumber,
} from "class-validator";
import { Type } from "class-transformer";
import { GymServiceCreateNestedManyWithoutGymsInput } from "./GymServiceCreateNestedManyWithoutGymsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class GymCreateInput {
  @ApiProperty({
    required: false,
    type: () => GymEquipmentCreateNestedManyWithoutGymsInput,
  })
  @ValidateNested()
  @Type(() => GymEquipmentCreateNestedManyWithoutGymsInput)
  @IsOptional()
  @Field(() => GymEquipmentCreateNestedManyWithoutGymsInput, {
    nullable: true,
  })
  gymEquipments?: GymEquipmentCreateNestedManyWithoutGymsInput;

  @ApiProperty({
    required: false,
    type: () => GymServiceCreateNestedManyWithoutGymsInput,
  })
  @ValidateNested()
  @Type(() => GymServiceCreateNestedManyWithoutGymsInput)
  @IsOptional()
  @Field(() => GymServiceCreateNestedManyWithoutGymsInput, {
    nullable: true,
  })
  gymServices?: GymServiceCreateNestedManyWithoutGymsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  payments?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  pricePerDay?: number | null;
}

export { GymCreateInput as GymCreateInput };
